os:
  - linux
language: node_js

jobs:
  include:
    - stage: "Build"
      script:
        - npm install -g typescript
        - npm install
        - npm run build:clean
    - stage: "Deploy"
      script:
        - npm install -g typescript
        - npm install
        - npm run build:clean
      deploy:
        provider: npm
        email: $NPM_EMAIL_ADDR
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true
          branch: master

notifications:
  email:
    recipients:
      - lucas@nindoo.ai
    on_success: change
    on_failure: always
